Repository dishamodi0910/APIVerse, pull requests merged in 2024-06, with the labels that each got.

#139 Quote-API added
  New_APIs/Quote_API/.gitignore
  New_APIs/Quote_API/README.md
  New_APIs/Quote_API/app.js
  New_APIs/Quote_API/package-lock.json
  New_APIs/Quote_API/package.json
  New_APIs/Quote_API/quotes.json
Labels: under-review, CHANGES-REQUESTED

#162 currency converter api implementation added
  Existing_API_Collection/Currency_Converter_API/README.md
  Existing_API_Collection/Currency_Converter_API/index.html
  Existing_API_Collection/Currency_Converter_API/script..js
  Existing_API_Collection/Currency_Converter_API/styles.css
  Existing_API_Collection/README.md
Labels: Merged🎊, level1

#169 Implement userlocation details by using Geolocation API and Nominatim API
  Existing_API_Collection/UserLocationAPI/userlocationdetails/.eslintrc.json
  Existing_API_Collection/UserLocationAPI/userlocationdetails/.gitignore
  Existing_API_Collection/UserLocationAPI/userlocationdetails/README.md
  Existing_API_Collection/UserLocationAPI/userlocationdetails/app/favicon.ico
  Existing_API_Collection/UserLocationAPI/userlocationdetails/app/globals.css
  Existing_API_Collection/UserLocationAPI/userlocationdetails/app/layout.js
  Existing_API_Collection/UserLocationAPI/userlocationdetails/app/page.js
  Existing_API_Collection/UserLocationAPI/userlocationdetails/jsconfig.json
  Existing_API_Collection/UserLocationAPI/userlocationdetails/next.config.mjs
  Existing_API_Collection/UserLocationAPI/userlocationdetails/package-lock.json
  Existing_API_Collection/UserLocationAPI/userlocationdetails/package.json
  Existing_API_Collection/UserLocationAPI/userlocationdetails/postcss.config.mjs
  Existing_API_Collection/UserLocationAPI/userlocationdetails/public/next.svg
  Existing_API_Collection/UserLocationAPI/userlocationdetails/public/vercel.svg
  Existing_API_Collection/UserLocationAPI/userlocationdetails/tailwind.config.js
Labels: Merged🎊, gssoc, level2

#161 result-marks api with more features
  New_APIs/README.md
  New_APIs/Result_Marks_API/Controllers/studentContoller.js
  New_APIs/Result_Marks_API/Controllers/teacherController.js
  New_APIs/Result_Marks_API/README.md
  New_APIs/Result_Marks_API/index.js
  New_APIs/Result_Marks_API/models/studentModel.js
  New_APIs/Result_Marks_API/models/teacherModel.js
  New_APIs/Result_Marks_API/package-lock.json
  New_APIs/Result_Marks_API/package.json
  New_APIs/Result_Marks_API/routes/studentRouter.js
  New_APIs/Result_Marks_API/routes/teacherRouter.js
Labels: under-review, CHANGES-REQUESTED

#164 json_placeholder api implementation added
  Existing_API_Collection/JSON_Placeholder_API/README.md
  Existing_API_Collection/JSON_Placeholder_API/index.html
  Existing_API_Collection/JSON_Placeholder_API/script.js
  Existing_API_Collection/README.md
Labels: under-review, CHANGES-REQUESTED
