Repository dishamodi0910/APIVerse, pull requests merged in 2024-08, with the labels that each got.

#327 added Countries API
  New_APIs/Countries_API/README.md
  New_APIs/Countries_API/countries.js
  New_APIs/Countries_API/package-lock.json
  New_APIs/Countries_API/package.json
  New_APIs/Countries_API/server.js
Labels: under-review, changes-requested

#344 Issue 101 - Added Github Desktop Contribution instructions
  CONTRIBUTING.md
Labels: gssoc, level1, gssoc24

#346 Issue number 345 - Barcode Generator API
  New_APIs/Barcode-Generator/Barcode Generator/READme.md
  New_APIs/Barcode-Generator/Barcode Generator/image.png
  New_APIs/Barcode-Generator/Barcode Generator/index.html
  New_APIs/Barcode-Generator/Barcode Generator/script.js
  New_APIs/Barcode-Generator/Barcode Generator/style.css
Labels: gssoc, level3, gssoc24

#338 [New API] : School & College Api
  New_APIs/Scool-College-api/Readme.md
  New_APIs/Scool-College-api/asset/Screenshot from 2024-07-22 08-14-21.png
  New_APIs/Scool-College-api/asset/Screenshot from 2024-07-22 08-14-51.png
  New_APIs/Scool-College-api/asset/Screenshot from 2024-07-22 08-15-04.png
  New_APIs/Scool-College-api/asset/Screenshot from 2024-07-22 08-15-14.png
  New_APIs/Scool-College-api/asset/data.js
  New_APIs/Scool-College-api/index.js
  New_APIs/Scool-College-api/package-lock.json
  New_APIs/Scool-College-api/package.json
Labels: gssoc, level3

#326 Added Anime Api
  Existing_API_Collection/Anime Api/README.md
  Existing_API_Collection/Anime Api/Src/__init__.py
  Existing_API_Collection/Anime Api/Src/objects.py
  Existing_API_Collection/Anime Api/Tests/test_anime_facts_rest_api.py
Labels: under-review, changes-requested

#320 Kartik
  Existing_API_Collection/Jokegenerator_API/README.md
  Existing_API_Collection/Jokegenerator_API/image.png
  Existing_API_Collection/Jokegenerator_API/index.html
  Existing_API_Collection/Jokegenerator_API/script.js
  Existing_API_Collection/Jokegenerator_API/style.css
Labels: under-review, changes-requested

#294 [New API] : URL Shortener API Added
  Existing_API_Collection/NasaAPI/index.html
  New_APIs/URL_shorten/Readme.md
  New_APIs/URL_shorten/controller/db.js
  New_APIs/URL_shorten/index.js
  New_APIs/URL_shorten/package-lock.json
  New_APIs/URL_shorten/package.json
  New_APIs/URL_shorten/server.js
Labels: under-review

#292 Solves issue#289
  Existing_API_Collection/Youtube-Data-API/README.md
  Existing_API_Collection/Youtube-Data-API/index.html
  Existing_API_Collection/Youtube-Data-API/script.js
  Existing_API_Collection/Youtube-Data-API/style.css
Labels: under-review

#236 the freeMeal api is added
  Existing_API_Collection/FreeMealsDB/index.html
  Existing_API_Collection/FreeMealsDB/script.js
  Existing_API_Collection/FreeMealsDB/style.css
Labels: under-review, changes-requested

#210 Covid 19 tracker API added
  Existing_API_Collection/Covid19Tracker API/README.md
  Existing_API_Collection/Covid19Tracker API/index.html
  Existing_API_Collection/Covid19Tracker API/script.js
  Existing_API_Collection/Covid19Tracker API/style.css
Labels: under-review, changes-requested

#207 F1 API
  New_APIs/F1_API/README.md
  New_APIs/F1_API/app.py
  New_APIs/F1_API/data.py
  New_APIs/F1_API/models/driver.py
  New_APIs/F1_API/models/race.py
  New_APIs/F1_API/models/team.py
  New_APIs/F1_API/resources/driver.py
  New_APIs/F1_API/resources/race.py
  New_APIs/F1_API/resources/team.py
Labels: under-review, changes-requested
